# Generated by Django 3.2.12 on 2023-03-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='News',
        ),
    ]
