# Generated by Django 3.2.12 on 2023-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_commentnews_newsaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
