# Generated by Django 3.2.12 on 2023-03-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0006_alter_commentnews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='quanly.role'),
        ),
    ]
