# Generated by Django 3.2.12 on 2023-03-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentnews',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'ordering': ['-id']},
        ),
    ]
