# Generated by Django 3.2.12 on 2023-03-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0008_auto_20230327_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
